Design/navbar-css
Corentin-kzk/GameOfGo pull request #29
Opened 2024-07-06 22:31 UTC by georgesim1

Updating the existing design of the navbar

2024-07-08 08:34 UTC, Corentin-kzk requested changes

2024-07-08 08:34 UTC, Corentin-kzk commented on front-end/package.json
> +    "lodash-es": "^4.17.21",
lodash-es ??

2024-07-08 08:34 UTC, Corentin-kzk commented on front-end/src/components/Navbar/Navbar.jsx
> +        </List>
chatgpt ?? / vérifier les valeurs et item n'est pas clair comme nom

2024-07-08 09:31 UTC, georgesim1 commented on front-end/package.json
> +    "lodash-es": "^4.17.21",
removed and fixed

2024-07-08 09:49 UTC, georgesim1 commented on front-end/src/components/Navbar/Navbar.jsx
> +        </List>
fixed this to resemble normal list items, it just added a lot more lines

2024-07-09 07:19 UTC, Eolran commented on front-end/src/components/Navbar/Navbar.jsx
> +const drawerWidth = 240;
?

2024-07-09 07:19 UTC, Eolran commented on front-end/src/theme/defaultTheme
No extension ?

2024-07-09 08:04 UTC, Eolran approved these changes

2024-07-09 08:06 UTC, Corentin-kzk approved these changes

2024-07-09 08:07 UTC, merged